### ISSUE TITLE
require 'json' instead of 'json'

### ISSUE THREAD

**Issue by timbleck** [bk-one/shoutbox-client#1]
On a Mac require 'json" and also require 'JSON' works fine but on a linux machine only require 'json' works so it should be changed to require 'json' to work on all machines.

```
linux $ irb -rubygems
> require 'json'
=> true 

linux $ irb -rubygems
> require 'JSON'
LoadError: no such file to load -- JSON
```

**Comment by bk-one** [comment]
thank you, fixed .. new gem comming up ..
